### ISSUE TITLE
Compile error while adding #addin "Cake.ExtendedNuGet"

### ISSUE THREAD

**Issue by avishnyakov** [Redth/Cake.ExtendedNuGet#7]
Once #addin "Cake.ExtendedNuGet" is added to a cakebuild the following error occurs:

```
Preparing to run build script...
Running build script...
Analyzing build script...
Processing build script...
Installing addins...
Compiling build script...
Error: error CS0246: The type or namespace name 'NuGet' could not be found (are you missing a using directive or an assembly reference?)
```

The cakebuild has only two tasks:

```
Task("Package-NuGet")
    .Does(() =>
{
    Information("Creating NuGet packages...");
});

//////////////////////////////////////////////////////////////////////
// TASK TARGETS
//////////////////////////////////////////////////////////////////////

Task("Default")
    .IsDependentOn("Package-NuGet");
```

**Comment by gep13** [comment]
@avishnyakov In order for this addin to work, I believe you will need to include:

```
#addin "nuget:?package=NuGet.Core&version=2.8.6"
```

In addition to the existing #addin that you have.  However, there might also be some other issues that need to be resolved as well.

/cc @Redth

**Comment by ristaloff** [comment]
Hi I just got a similar issue. When I only have this line:
```
#addin "Cake.ExtendedNuGet"
```
I get this error:
````
Installing addins... Could not load C:\vcs\git\EBS\ebslibs\EBS.Logging\build\tools\Addins\Cake.ExtendedNuGet\lib\net45\Cake.ExtendedNuGet.dll (missing NuGet.Core, Version=2.8.60717.93, Culture=neutral, PublicKeyToken=31bf3856ad364e35))
Compiling build script...
Error: error CS0246: The type or namespace name 'NuGet' could not be found (are you missing a using directive or an assembly reference?)
```

When I add this:
```
#addin "nuget:?package=NuGet.Core&version=2.8.6"
```
I get:
```
Error: error CS1705: Assembly 'Cake, Version=0.16.0.0, Culture=neutral, PublicKeyToken=null' uses 'NuGet.Core, Version=2.12.0.817, Culture=neutral, PublicKeyToken=31bf3856ad364e35' which has a higher version than referenced assembly 'NuGet.Core, Version=2.8.60717.93, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
```

**Comment by kal** [comment]
I just hit the same problem. I think it is fixed by changing the line to:

```
#addin "nuget:?package=NuGet.Core&version=2.12.0"
```

I found that I then had to delete the tools directory to flush out the out-of-date dependency.

**Comment by vip32** [comment]
when i add both nuget addins (nuget.core & etendednuget) i suddenly get the following error when compiling my cake script

Error: System.NullReferenceException: Object reference not set to an instance of an object.
   at Roslyn.Compilers.CodeGen.ReflectionEmitter.GetToken(MemberInfo member)
   at Roslyn.Compilers.CodeGen.ReflectionEmitter.SubstituteTokens(Byte[] buffer)
   at Roslyn.Compilers.CodeGen.ReflectionEmitter.EmitMethodBody(MethodBuilder methodBuilder, ConstructorBuilder constructorBuilder, IMethodBody body)
   at Roslyn.Compilers.CodeGen.ReflectionEmitter.Emit(CancellationToken cancellationToken, IMethodReference entryPoint)
   at Roslyn.Compilers.CSharp.Compilation.Emit(ModuleBuilder moduleBuilder, IAssemblyLoader assemblyLoader, Func`2 assemblySymbolMapper, CancellationToken cancellationToken, Boolean recoverOnError, ReadOnlyArray`1& compiledAssemblyImage)
   at Roslyn.Compilers.CSharp.Compilation.CommonEmit(ModuleBuilder moduleBuilder, IAssemblyLoader assemblyLoader, Func`2 assemblySymbolMapper, CancellationToken cancellationToken, Boolean recoverOnError, ReadOnlyArray`1& compiledAssemblyImage)
   at Roslyn.Scripting.CommonScriptEngine.TryEmitSubmission(CommonCompilation compilation, DiagnosticBag diagnostics, Type delegateType, Boolean collectible, CancellationToken cancellationToken, Delegate& factory)
   at Roslyn.Scripting.CommonScriptEngine.Compile(String code, String path, DiagnosticBag diagnostics, Session session, Type delegateType, Type returnType, CancellationToken cancellationToken, Boolean isInteractive, Boolean isExecute, CommonCompilation& compilation, Delegate& factory)
   at Roslyn.Scripting.CommonScriptEngine.Execute[T](String code, String path, DiagnosticBag diagnostics, Session session, Boolean isInteractive)
   at Roslyn.Scripting.Session.Execute(String code)
   at Cake.Core.Scripting.ScriptRunner.Run(IScriptHost host, FilePath scriptPath, IDictionary`2 arguments)
   at Cake.Commands.BuildCommand.Execute(CakeOptions options)
   at Cake.CakeApplication.Run(CakeOptions options)
   at Cake.Program.Main()

in that cake script extendednuget is not even used.

**Comment by gep13** [comment]
@vip32 I have seen this issue before, and I have tried to speak to @Redth about it, but not had a proper chance yet.  For now, try running with the `-Experimental` flag.  That should get you up and running again.

**Comment by vip32** [comment]
ow nice, that did the trick. thx for helping out!

**Comment by vip32** [comment]
strange, when now using the GetPackageReferences(DirectoryPath) alias i get the following error during task execution.

''
var path = Cake.Core.IO.DirectoryPath.FromString(...mypath string);
GetPackageReferences(path);

''
Error: System.MissingMethodException: Method not found: 'System.Collections.Generic.IEnumerable`1<NuGet.PackageReference> Cake.ExtendedNuGet.ExtendedNuGetAliases.GetPackageReferences(Cake.Core.ICakeContext, Cake.Core.IO.DirectoryPath)'.
   at Submission#0.GetPackageReferences(DirectoryPath path)
   at Submission#0.<.ctor>b__357_1()
   at Cake.Core.ActionTask.Execute(ICakeContext context)
   at Cake.Core.DefaultExecutionStrategy.Execute(CakeTask task, ICakeContext context)
   at Cake.Core.CakeEngine.ExecuteTask(ICakeContext context, IExecutionStrategy strategy, Stopwatch stopWatch, CakeTask task, CakeReport report)
   at Cake.Core.CakeEngine.RunTarget(ICakeContext context, IExecutionStrategy strategy, String target)
   at Cake.Scripting.BuildScriptHost.RunTarget(String target)
   at Submission#0..ctor(Object[] submissionArray, Object& submissionResult)
   at Submission#0.<Factory>(Object[] submissionArray)
   at Microsoft.CodeAnalysis.Scripting.ScriptExecutionState.RunSubmission(Func`2 submissionRunner)
   at Microsoft.CodeAnalysis.Scripting.Script.Run(Object globals)
   at Microsoft.CodeAnalysis.Scripting.Script.Run(Object globals)
   at Cake.Scripting.Roslyn.Nightly.DefaultRoslynNightlyScriptSession.Execute(Script script)
   at Cake.Core.Scripting.ScriptRunner.Run(IScriptHost host, FilePath scriptPath, IDictionary`2 arguments)
   at Cake.Commands.BuildCommand.Execute(CakeOptions options)
   at Cake.CakeApplication.Run(CakeOptions options)
   at Cake.Program.Main()

i checked the ExtendedNuget dll (1.0.022) however that contains the offending method.

**Comment by gep13** [comment]
@vip32 I believe that issue is covered in this PR: https://github.com/Redth/Cake.ExtendedNuGet/pull/10

**Comment by vip32** [comment]
clear, let's wait for the PR then

**Comment by ChrisMaddock** [comment]
Thanks all - I've just hit the same problem. Just to clarify for future readers, using Cake 17.0, I required:
```
#addin "Cake.ExtendedNuGet"
#addin "nuget:?package=NuGet.Core&version=2.8.6"
```

And the `-Experiemental` flag on the command line.

**Comment by MCCoolMoDAue** [comment]
I am trying to use 
`#addin "Cake.ExtendedNuGet"`
and I cannot get it to work.
basically with the same problem:
`Error: error CS1705: Assembly 'Cake, Version=0.19.4.0, Culture=neutral, PublicKeyToken=null' uses 'NuGet.Core, Version=2
.12.0.817, Culture=neutral, PublicKeyToken=31bf3856ad364e35' which has a higher version than referenced assembly 'NuGet.
Core, Version=2.8.60717.93, Culture=neutral, PublicKeyToken=31bf3856ad364e35'`

As you can see I am using cake 0.19.4
I also tried the -Experimental flag, but it didn't work.

Is there something i can try out?

**Comment by MCCoolMoDAue** [comment]
Am I wrong to say that this add-in is broken as it is?
I cannot see how this add-in can not be used at all.
Previous workarounds do not seem to work any longer.
Is this project still active?

**Comment by Redth** [comment]
Interesting, this should in theory work.... I'll have to dig in a bit further...

**Comment by JFMG** [comment]
I just installed the addin and cannot get it to work because of the described bug above. The described workaround do not work for me

**Comment by WalkerCodeRanger** [comment]
The NuGet.Core package should be listed as a dependency in the nuspec file so that it is automatically pulled down.

**Comment by Redth** [comment]
This shouldn't be an issue now.
